name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  library:
    runs-on: macos-11
    environment: default
    strategy:
      fail-fast: false
      matrix:
        platform: [macOS]
        xcode: [12.4, 12.5.1, 13.2]
        # Swift: 5.3, 5.4.2, 5.5.2
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
#       - name: Select Xcode ${{ matrix.xcode }}
#         run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - run: ifconfig
      - name: Format lint
        run: swiftformat --lint .
      - name: Lint
        run: swiftlint .
      - name: Run Tests
        run: swift test --enable-code-coverage --parallel
      - name: Swift Coverage Report
        uses: maxep/spm-lcov-action@0.3.1
      - name: Code Coverage
        run: bash <(curl -s https://codecov.io/bash) -X xcodellvm
